apiVersion: v1
kind: Service
metadata:
  name: canary-demo
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
    nodePort: 31000
  selector:
    app: canary-demo
  type: NodePort
